In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('houseprice.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [3]:
df.shape

(1201, 10)

In [4]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [4]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique())))

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597


In [5]:
import datetime
datetime.datetime.now().year

2023

In [6]:
df['Total Years']=datetime.datetime.now().year-df['YearBuilt']

In [9]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  Total Years  
0       856       854     208500           20  
1      1262         0     181500           47  
2       920       866     223500           22  
3       961       756     140000          108  
4      1145      1053     250000           23

In [7]:

df.drop("YearBuilt",axis=1,inplace=True)

In [11]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total Years'],
      dtype='object')

In [8]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]
out_feature="SalePrice"

In [9]:
df["MSSubClass"].unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  80, 160,  75, 180,
        40,  85])

In [10]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0])

In [11]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature])

In [17]:
df.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           20  
1         0     181500           47  
2       866     223500           22  
3       756     140000          108  
4      1053     250000           23

In [12]:
### Stacking and Converting Into Tensors
import numpy as np
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [13]:
### Convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [14]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i)

In [22]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [15]:
### Stacking continuous variable to a tensor
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    20.],
        [   80.,  9600.,  1262.,     0.,    47.],
        [   68., 11250.,   920.,   866.,    22.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    82.],
        [   68.,  9717.,  1078.,     0.,    73.],
        [   75.,  9937.,  1256.,     0.,    58.]])

In [24]:
cont_values.dtype

torch.float32

In [16]:
### Dependent Feature
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int64  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int64  
 5   LotShape     1201 non-null   int64  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total Years  1201 non-null   int64  
dtypes: float64(1), int64(9)
memory usage: 103.2 KB


In [29]:
df.shape

(1201, 10)

In [30]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [18]:
#### Embedding Size For Categorical columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]]

In [19]:
cat_dims

[15, 5, 2, 4]

In [20]:
embedding_dim= [(x, min(50, (x + 1) // 2)) for x in cat_dims]

In [21]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [22]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [24]:
cat_features


tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [25]:
cat_featuresz=cat_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [26]:
pd.set_option('display.max_rows', 500)
embedding_val=[]
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i]))

In [27]:
embedding_val

[tensor([[-0.4774, -1.2273,  1.0294,  ...,  0.8534, -0.5784,  1.2883],
         [-0.0394,  0.5511,  1.3840,  ..., -1.5124, -0.7369, -0.3806],
         [-0.4774, -1.2273,  1.0294,  ...,  0.8534, -0.5784,  1.2883],
         ...,
         [ 1.0093, -0.6096, -1.2262,  ..., -0.0443,  0.1400,  0.5435],
         [-0.0394,  0.5511,  1.3840,  ..., -1.5124, -0.7369, -0.3806],
         [-0.0394,  0.5511,  1.3840,  ..., -1.5124, -0.7369, -0.3806]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.4862,  0.0491, -2.5565],
         [ 0.4862,  0.0491, -2.5565],
         [ 0.4862,  0.0491, -2.5565],
         ...,
         [ 0.4862,  0.0491, -2.5565],
         [ 0.4862,  0.0491, -2.5565],
         [ 0.4862,  0.0491, -2.5565]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.0077],
         [0.0077],
         [0.0077],
         ...,
         [0.0077],
         [0.0077],
         [0.0077]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.5067,  0.8600],
         [ 0.5067,  0.8600],
         [ 0.8746, -0.7849],

In [28]:
z = torch.cat(embedding_val, 1)

In [29]:
z

tensor([[-0.4774, -1.2273,  1.0294,  ...,  0.0077,  0.5067,  0.8600],
        [-0.0394,  0.5511,  1.3840,  ...,  0.0077,  0.5067,  0.8600],
        [-0.4774, -1.2273,  1.0294,  ...,  0.0077,  0.8746, -0.7849],
        ...,
        [ 1.0093, -0.6096, -1.2262,  ...,  0.0077,  0.5067,  0.8600],
        [-0.0394,  0.5511,  1.3840,  ...,  0.0077,  0.5067,  0.8600],
        [-0.0394,  0.5511,  1.3840,  ...,  0.0077,  0.5067,  0.8600]],
       grad_fn=<CatBackward0>)

In [30]:
#### Implement dropupout
droput=nn.Dropout(.4)



In [31]:
final_embed=droput(z)
final_embed

tensor([[-0.7957, -0.0000,  0.0000,  ...,  0.0000,  0.8445,  1.4334],
        [-0.0657,  0.9184,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0000, -2.0455,  1.7157,  ...,  0.0128,  0.0000, -1.3082],
        ...,
        [ 0.0000, -0.0000, -0.0000,  ...,  0.0128,  0.8445,  1.4334],
        [-0.0657,  0.9184,  2.3067,  ...,  0.0000,  0.0000,  1.4334],
        [-0.0000,  0.9184,  2.3067,  ...,  0.0128,  0.8445,  0.0000]],
       grad_fn=<MulBackward0>)

In [32]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module):

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)

        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim))
        n_in = n_emb + n_cont

        for i in layers:
            layerlist.append(nn.Linear(n_in,i))
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))

        self.layers = nn.Sequential(*layerlist)

    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)

        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [33]:
len(cont_features)

5

In [34]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [35]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

Define Loss And Optimizer

In [37]:
loss_function=nn.MSELoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [36]:
model.parameters

<bound method Module.parameters of FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)>

In [38]:
df.shape

(1201, 10)

In [39]:
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [40]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [41]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 200496.75
Epoch number: 11 and the loss : 200493.46875
Epoch number: 21 and the loss : 200489.140625
Epoch number: 31 and the loss : 200482.640625
Epoch number: 41 and the loss : 200473.25
Epoch number: 51 and the loss : 200461.375
Epoch number: 61 and the loss : 200446.4375
Epoch number: 71 and the loss : 200429.421875
Epoch number: 81 and the loss : 200407.953125
Epoch number: 91 and the loss : 200383.421875
Epoch number: 101 and the loss : 200355.234375
Epoch number: 111 and the loss : 200322.109375
Epoch number: 121 and the loss : 200291.578125
Epoch number: 131 and the loss : 200252.0
Epoch number: 141 and the loss : 200206.296875
Epoch number: 151 and the loss : 200162.9375
Epoch number: 161 and the loss : 200112.03125
Epoch number: 171 and the loss : 200059.4375
Epoch number: 181 and the loss : 200006.109375
Epoch number: 191 and the loss : 199946.59375
Epoch number: 201 and the loss : 199881.75
Epoch number: 211 and the loss : 199816.125
Epoch num

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(range(epochs), final_losses)
plt.ylabel('RMSE Loss')
plt.xlabel('epoch');

In [43]:
#### Validate the Test Data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE: {}'.format(loss))

RMSE: 40477.4609375


In [45]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])

In [46]:
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [47]:
data_verify

Test
0    130000.0
1    138887.0
2    175500.0
3    195000.0
4    142500.0
5    265900.0
6    224900.0
7    248328.0
8    170000.0
9    465000.0
10   178000.0
11   186500.0
12   129500.0
13   119000.0
14   244000.0
15   130000.0
16   165400.0
17   127500.0
18   301500.0
19    99900.0
20   190000.0
21   151000.0
22   128900.0
23   180500.0
24   181000.0
25   183900.0
26   122000.0
27   378500.0
28   144000.0
29   177000.0
30   139000.0
31   137000.0
32   237000.0
33    68400.0
34   227000.0
35   180000.0
36   150500.0
37   139000.0
38   169000.0
39   132500.0
40   278000.0
41   281000.0
42   119500.0
43   107500.0
44   162900.0
45   115000.0
46   138500.0
47   155000.0
48   140000.0
49   160000.0
50   154000.0
51   290000.0
52   232000.0
53   130000.0
54   325000.0
55   202500.0
56   138000.0
57   147000.0
58   335000.0
59   203000.0
60   333168.0
61   119000.0
62   206900.0
63   295493.0
64   208900.0
65   111000.0
66   156500.0
67   190000.0
68    82500.0
69   147000.0
70    55000.0
71    79000.0
72   130500.0
73   256000.0
74   176500.0
75   227000.0
76   132500.0
77   100000.0
78   125500.0
79   125000.0
80   167900.0
81   135000.0
82    52500.0
83   200000.0
84   128500.0
85   123000.0
86   155000.0
87   177000.0
88   155835.0
89   108500.0
90   283463.0
91   122000.0
92   200000.0
93   171000.0
94   134900.0
95   410000.0
96   170000.0
97   315000.0
98   189000.0
99   260000.0
100  156932.0
101  144152.0
102  193000.0
103  127000.0
104  232000.0
105  105000.0
106  165500.0
107  274300.0
108  250000.0
109  239000.0
110   91000.0
111  117000.0
112   83000.0
113  167500.0
114   58500.0
115  157000.0
116  105000.0
117  125500.0
118  250000.0
119  136000.0
120  377500.0
121  131000.0
122  235000.0
123  124000.0
124  123000.0
125  163000.0
126  246578.0
127  281213.0
128  137500.0
129  138000.0
130  137450.0
131  120000.0
132  193000.0
133  193879.0
134  282922.0
135  105000.0
136  275000.0
137  133000.0
138  125500.0
139  215000.0
140  230000.0
141  140000.0
142   90000.0
143  257000.0
144  207000.0
145  175900.0
146  122500.0
147  124000.0
148  179900.0
149  127500.0
150  136500.0
151  142000.0
152  271000.0
153  140000.0
154  119000.0
155  192140.0
156   64500.0
157  186500.0
158  160000.0
159  174000.0
160  120500.0
161  394617.0
162  149700.0
163  197000.0
164  191000.0
165  310000.0
166  179600.0
167  129000.0
168  240000.0
169  112000.0
170   92000.0
171  136000.0
172  287090.0
173  145000.0
174   84500.0
175  185000.0
176  175000.0
177  210000.0
178  266500.0
179  142125.0

In [48]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head()

Test     Prediction    Difference
0  130000.0  118166.890625  11833.109375
1  138887.0  219049.218750 -80162.218750
2  175500.0  127814.625000  47685.375000
3  195000.0  235170.750000 -40170.750000
4  142500.0  210654.843750 -68154.843750

In [49]:
final_output

Test     Prediction     Difference
0    130000.0  118166.890625   11833.109375
1    138887.0  219049.218750  -80162.218750
2    175500.0  127814.625000   47685.375000
3    195000.0  235170.750000  -40170.750000
4    142500.0  210654.843750  -68154.843750
5    265900.0  205635.062500   60264.937500
6    224900.0  157286.375000   67613.625000
7    248328.0  316152.593750  -67824.593750
8    170000.0  150613.578125   19386.421875
9    465000.0  388799.156250   76200.843750
10   178000.0  216236.984375  -38236.984375
11   186500.0  188186.937500   -1686.937500
12   129500.0  175864.312500  -46364.312500
13   119000.0  110382.234375    8617.765625
14   244000.0  188433.218750   55566.781250
15   130000.0  106684.398438   23315.601562
16   165400.0  238785.343750  -73385.343750
17   127500.0  126735.953125     764.046875
18   301500.0  323178.156250  -21678.156250
19    99900.0   86557.351562   13342.648438
20   190000.0  192373.312500   -2373.312500
21   151000.0  119452.250000   31547.750000
22   128900.0   91351.156250   37548.843750
23   180500.0  173964.031250    6535.968750
24   181000.0  156792.656250   24207.343750
25   183900.0  193080.734375   -9180.734375
26   122000.0  137483.984375  -15483.984375
27   378500.0  359699.031250   18800.968750
28   144000.0  148279.921875   -4279.921875
29   177000.0  142031.953125   34968.046875
30   139000.0   77660.726562   61339.273438
31   137000.0  134147.015625    2852.984375
32   237000.0  263451.968750  -26451.968750
33    68400.0   62396.746094    6003.253906
34   227000.0  234588.656250   -7588.656250
35   180000.0  200798.312500  -20798.312500
36   150500.0  125274.359375   25225.640625
37   139000.0  135081.390625    3918.609375
38   169000.0  166101.250000    2898.750000
39   132500.0  113224.312500   19275.687500
40   278000.0  263296.750000   14703.250000
41   281000.0  318239.781250  -37239.781250
42   119500.0   79953.632812   39546.367188
43   107500.0  180308.593750  -72808.593750
44   162900.0  191530.343750  -28630.343750
45   115000.0  106678.578125    8321.421875
46   138500.0  102786.718750   35713.281250
47   155000.0  142492.468750   12507.531250
48   140000.0  162980.578125  -22980.578125
49   160000.0  387085.062500 -227085.062500
50   154000.0  132140.468750   21859.531250
51   290000.0  353284.250000  -63284.250000
52   232000.0  236303.031250   -4303.031250
53   130000.0  144424.375000  -14424.375000
54   325000.0  262479.406250   62520.593750
55   202500.0  192250.625000   10249.375000
56   138000.0  130969.609375    7030.390625
57   147000.0  116127.000000   30873.000000
58   335000.0  278438.656250   56561.343750
59   203000.0  183924.140625   19075.859375
60   333168.0  336656.968750   -3488.968750
61   119000.0  120652.781250   -1652.781250
62   206900.0  221995.593750  -15095.593750
63   295493.0  244984.718750   50508.281250
64   208900.0  171456.687500   37443.312500
65   111000.0  135097.468750  -24097.468750
66   156500.0  162118.890625   -5618.890625
67   190000.0  261423.062500  -71423.062500
68    82500.0   56538.542969   25961.457031
69   147000.0  260857.375000 -113857.375000
70    55000.0   75006.500000  -20006.500000
71    79000.0   69789.179688    9210.820312
72   130500.0   89977.687500   40522.312500
73   256000.0  303563.593750  -47563.593750
74   176500.0  198652.578125  -22152.578125
75   227000.0  237809.125000  -10809.125000
76   132500.0  144506.531250  -12006.531250
77   100000.0  110807.929688  -10807.929688
78   125500.0  122586.531250    2913.468750
79   125000.0  106997.078125   18002.921875
80   167900.0  147884.203125   20015.796875
81   135000.0  133608.390625    1391.609375
82    52500.0   78180.828125  -25680.828125
83   200000.0  257557.046875  -57557.046875
84   128500.0  122033.578125    6466.421875
85   123000.0   98299.609375   24700.390625
86   155000.0  147500.843750    7499.156250
87   177000.0  139080.109375   37919.890625
88   155835.0  155645.812500     189.187500
89   108500.0   93925.414062   14574.585938
90   

In [50]:
#### Saving The Model
#### Save the model
torch.save(model,'HousePrice.pt')

In [51]:
#### Saving The Model
#### Save the model
torch.save(model,'HousePrice.pt')

In [54]:
torch.save(model.state_dict(),'HouseWeights.pt')

In [52]:
### Loading the saved Model
embs_size=[(15, 8), (5, 3), (2, 1), (4, 2)]
model1=FeedForwardNN(embs_size,5,1,[100,50],p=0.4)

In [55]:
model1.load_state_dict(torch.load('HouseWeights.pt'))

<All keys matched successfully>

In [56]:
model1.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)